# Change these first
owner: NTHU-SA # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
    - name: NTHU Data API by NTHUSA
      url: https://api.nthusa.tw
    - name: 國立清華大學 eeclass 數位學習平台
      url: https://eeclass.nthu.edu.tw/
    - name: 清華 eLearn 數位學習平台
      url: https://elearn.nthu.edu.tw/

status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    cname: status.nthusa.tw
    # baseUrl: /your-repo-name
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: NTHU Status Page
    introTitle: "**Monitor the status of NTHU services.** Powered by Upptime."
    introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/NTHU-SA/upptime).
    navbar:
        - title: Status
          href: /
        - title: GitHub
          href: https://github.com/NTHU-SA
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
